#!/usr/bin/env bash
#  Bash script that displays "To infinity and beyond" indefinitely.

while :
do
	echo "To infinity and beyond"
	sleep 2
	if ( trap SIGTERM );
	then
		echo "I am invincible!!!"
	fi

done
