#!/usr/bin/env bash
# displays numbers from 1 to 20 and
i=1
while [ $i -lt 21 ]
do
	if [ $i = 5 ]
	then
		echo "bad luck from China"
	elif [ $i = 10 ]
	then
		echo "bad luck from Japan"
	elif [ $i = 18 ]
	then
		echo "bad luck from Italy"
	else
		echo $i
	fi
		(( i++ ))
done
